title: 			 rOpenSci Newsletter
email: 			 info@ropensci.org
description: "rOpenSci Newsletter, including software, software reviews, what's happening in the community, events, and more."
permalink:   "/:slug/"
twitter_username: ropensci
github_username:  ropensci
author: ropensci

markdown: kramdown

exclude: ["posts_heatmap_calendar.md", "ignore", "Makefile", "scripts/", "README.md", "data", "anystyle.rb"]
