title: 			 rOpenSci News
email: 			 info@ropensci.org
description: "rOpenSci twice monthly updates, including for software, software review news, what's happening in the community, events, and more."
url: 				 "http://biweekly.ropensci.org"
baseurl:     "/biweekly"
permalink:   "/:title/"
twitter_username: ropensci
github_username:  ropensci

markdown: kramdown
